{% set name = "aiida-wannier90_workflows" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 014ada7badb863537363e5a3449644f179c7f2909d6144312a1d6e76546580d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - reentry
  run:
    - aiida-core >=2.0,<3
    - aiida-pseudo >=0.6
    - aiida-quantumespresso >=4.4
    - aiida-wannier90 >=2.1
    - python >=3.8
    - click >=8.0
    - colorama

test:
  imports:
    - aiida_wannier90_workflows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiidateam/aiida-wannier90-workflows
  summary: Advanced AiiDA workflows for Wannier90
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
