{% set name = "aiida-wannier90_workflows" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 02ae490d2cad26cbed041372952c02b714e3eb98e6ef10d507315c54ba9c209a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - reentry
  run:
    - aiida-core >=1.1.1,<2
    - aiida-quantumespresso >=3.0.0a6
    - aiida-wannier90 >=2.0.0
    - python >=3.6

test:
  imports:
    - aiida_wannier90_workflows
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiidateam/aiida-wannier90-workflows
  summary: Advanced AiiDA workflows for Wannier90
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
